### PR TITLE
Create ci.yml

### PR DESCRIPTION
**Pull request by simonbyrne**

### CODE REVIEW

**Comment by ViralBShah** [comment]
We probably want to go with `create_sysimage()` to avoid having to deal with OS specific stuff.

https://julialang.github.io/PackageCompiler.jl/dev/sysimages/

**Comment by simonbyrne** [comment]
I tried, but I couldn't figure out how to use `@ccallable` with `create_sysimage()`.

**Comment by KristofferC** [comment]
> I tried, but I couldn't figure out how to use @ccallable with create_sysimage().

What are the particular problems with it? It should just put the unmangled symbol in there.

**Comment by simonbyrne** [comment]
> > I tried, but I couldn't figure out how to use @ccallable with create_sysimage().
> 
> What are the particular problems with it? It should just put the unmangled symbol in there.

I didn't realise that you have to put the `@ccallable` in the `script` argument.

**Comment by KristofferC** [comment]
Where did you put it before? It should be able to go into e.g. a package as well.

**Pull request merged**
